travis:
  secure:
    BINSTAR_TOKEN: eTRV6iP/5LGnjR62rCGbk79fu1jEz86l6rIbycUfKf+A9TPYfEYi+IX1Qrpl4sNUz8djr94/WWNxt8pabOdv1x0Ttqn2DptGLuJ+BJ1PkgbvywSRPltFotQsTWI8fhbKHK+c7J8iGzdSwDFBG4Xh7f1Zu4j1xP/znLo8Ai4fNs2oVVGVC/I+hLyeyaTJ8rapE4MO0vQDnVqB+0xT+ef5E6OME47aKqIWZxWBWRbqyxyFoHMWg8BZXy8IBCbC57vdj1DJuM6MDc4q7TM/DSih9NhWauzaf3zpeX07WdOW0jNsZKgujV6DVxYMhXetRyJFC5UFMLF5iSf9BWxy40c/sn9WbbJ4PiM9HQZocAYYq07LaaXs89BvAIgp/yJXuUVBneGgUtCepwC1jUvo7SmUwdhf8BleRu39ccMbgfQJGVO9DyJ3epqL3fX/QPlh6iOkNFUUHTLicKCg4X4dub9Fr1FUWWVFNBQB63ADaTGrO49P2VaFmwZ4JsxEtzsdUXwB+GS20eaC7j/sKAbktMSlRLBppfMiy1r97Ra9CPbJYrCSxcvDxVgaUFxD2DiZzqygzAj8Btp6IyOMW4ZdU7jcNs/2AShfGdGrEokS8znKVCquE8ytxl7dgDo+viBrNmNmcR3pJ8S1g5P5fRiUPKCykSXoZA6K7c7td36NlrdJ9Nw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
